name: CI

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                module: [".", linter]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: stable
            - run: go test -race ./...
              working-directory: ${{ matrix.module }}

    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                module: [".", linter]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: stable
            - uses: golangci/golangci-lint-action@v8
              with:
                  version: latest
                  working-directory: ${{ matrix.module }}
